name: Build & deploy teste 

on:
 pull_request:
   branches:
     - dev
defaults:
  run:
   working-directory: ./backend
jobs:
 build:
   name: Build
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [14.x]
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}
   - name: Install Packages
     run: npm install
   - name: Upload production-ready build files
     uses: actions/upload-artifact@v2
     with:
       name: production-files
       path: ./build
 deploy:
   name: Deploy
   needs: build
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - uses: akhileshns/heroku-deploy@v3.12.12 
     with:
       heroku_api_key: ${{secrets.HEROKU_API_KEY}}
       heroku_app_name: "fashion-shop-backend"
       eroku_email: "emanuelcascone@gmail.com"